version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:13-3.1-alpine
    command: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/init/postgres/init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
